---
services:
  db:
    image: postgres:18-bookworm
    command: ["postgres", "-c", "max_connections=200"]
    ports:
      - "5544:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Berlin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
